### ISSUE TITLE
Metrics parser is not working in time format ISO8601

### ISSUE THREAD

**Issue by mtulio** [rvanderp3/esxtop-grafana#1]
Metrics parser is not working in time format ISO8601 and delimiter ";" (not sure if the standard one is ',' or ';')
~~~
>>>> Opened metrics.csv
Traceback (most recent call last):
  File "//start.py", line 5, in <module>
    from esxtop_metric_server import esxtop_bp
  File "/esxtop_metric_server.py", line 171, in <module>
    reloadMetrics()
  File "/esxtop_metric_server.py", line 164, in reloadMetrics
    metrics["time"].append(timeToMillis(columns[0].replace('"', '')))
  File "/esxtop_metric_server.py", line 124, in timeToMillis
    return datetime.strptime(time,'%m/%d/%Y %H:%M:%S').timestamp()
  File "/usr/local/lib/python3.9/_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/usr/local/lib/python3.9/_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data '2021-04-28T21:17:00.000Z;88;0;52;1;0;0;0;0;3;0;0;0;0;4;0;5;0;20;0;0;4263;49;2896;0;0;0;302;0;0;0;0;1;0;0;0;1014;4352\n' does not match format '%m/%d/%Y %H:%M:%S'
1
podman start -a esxtop-grafana_grafana_1
~~~

A working arround is in progress in https://github.com/mtulio/esxtop-grafana/tree/devel

**Comment by mtulio** [comment]
I've created a script to parser non-standard csv headers exported by vCenter. Trying to adapt to server_parser.

Look to the temporary script:
~~~python
import csv, json
from os import listdir
from os.path import isfile, join


csvFile = './data/esxtop/metrics.csv'
csvDir = './data/esxtop'


metrics = []
metrics_by_csv = {}
date_key = ""


for fname in listdir(csvDir):
    fullPath = join(csvDir, fname)
    if isfile(fullPath) and fname[0] != "." :
        with open(fullPath, 'r') as f:
            csvReader = csv.DictReader(f, delimiter=";")
            metrics_by_csv[fname] = {}
            for row in csvReader:
                first_field = True
                date_key = ""
                for row_k in row.keys():
                    if first_field:
                        date_key = row_k
                        first_field = False
                        continue
                    try:
                        dummy = metrics_by_csv[fname][row_k]
                    except KeyError:
                        metrics_by_csv[fname][row_k] = []
                        pass
                    except:
                        raise
                    metrics_by_csv[fname][row_k].append({
                        "time": row[date_key],
                        "value": row[row_k]
                    })


print(json.dumps(metrics_by_csv))
~~~

The output will be something like this:
~~~json
{
  "file_name": {
    "metric_name": [
       {
          "timestamp": date:timestamp,
           "value": float:measurement_value
        }
     ]
  }
}

~~~
